// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwsvnovamklzumswnofq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3c3Zub3ZhbWtsenVtc3dub2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNTg3OTcsImV4cCI6MjA2NjkzNDc5N30.lBEzXSu-TpYjHePzwQ0xoARXzaZTNQNsTaj36qY6r7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});